general {
    lock_cmd = hyprlock
    unlock_cmd = loginctl unlock-session
    before_sleep_cmd = hyprctl dispatch dpms off
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Animated screensaver after 15 minutes
listener {
    timeout = 900
    on-timeout = ~/.config/hypr/scripts/screensaver.sh start
    on-resume = ~/.config/hypr/scripts/screensaver.sh stop
}