##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = match:floating false, match:onworkspace w[tv1], border_size 0
# windowrule = match:floating false, match:onworkspace w[tv1], rounding 0
# windowrule = match:floating false, match:onworkspace f[1], border_size 0
# windowrule = match:floating false, match:onworkspace f[1], rounding 0

# Example windowrule
# windowrule = match:class ^(kitty)$, match:title ^(kitty)$, float on

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false

# Layer rules
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha on, match:namespace rofi
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.1, match:namespace waybar
layerrule = ignore_alpha on, match:namespace wofi
layerrule = blur on, match:namespace waybar_widgets
layerrule = ignore_alpha on, match:namespace waybar_widgets
